language: node_js
dist: trusty
sudo: required
node_js: 5
install:
  - npm install
  - npm install -g bower
  - bower install
script:
  - npm test
  - npm run example-ace
  - npm run example-ajax
  - npm run example-components
  - npm run example-counter
  - npm run example-deep-peek
  - npm run example-interpret
  - npm run example-intro
  - npm run example-keyboard-shortcuts
  - npm run example-lifecycle
  - npm run example-multi-component
  - npm run example-todo
after_success:
- >-
  test $TRAVIS_TAG &&
  node_modules/.bin/psc-publish > .pursuit.json &&
  curl -X POST http://pursuit.purescript.org/packages \
    -d @.pursuit.json \
    -H 'Accept: application/json' \
    -H "Authorization: token ${GITHUB_TOKEN}"
