language: node_js
sudo: false
node_js:
  - 0.12
install:
  - npm install
script:
  - npm run build
  - npm run example-ace
  - npm run example-ajax
  - npm run example-components
  - npm run example-counter
  - npm run example-interpret
  - npm run example-intro
  - npm run example-multi-component
  - npm run example-todo
