language: node_js
dist: trusty
sudo: required
node_js: 5
install:
  - npm install
  - npm install -g bower
  - bower install
script:
  - npm run build
  - npm test
  - npm run example-ace
  - npm run example-ajax
  - npm run example-components
  - npm run example-counter
  - npm run example-interpret
  - npm run example-intro
  - npm run example-keyboard-shortcuts
  - npm run example-lifecycle
  - npm run example-multi-component
  - npm run example-todo
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
